# use on the one host
- name: "install_docker_specific_or_latest_version"
  hosts: "{{ HOST }}"
  gather_facts: true
  vars:
    github_docker_compose_plugin: https://github.com/docker/compose/releases
    latest_release: https://api.github.com/repos/docker/compose/releases/latest
  become: yes
  tasks:
# \============= debug =============  
  # - name: Show facts
  #   debug:
  #     msg: "{{ ansible_facts }}"
  #   when: true

  # - name: Show var
  #   debug:
  #     msg: "{{ ansible_facts.distribution | lower }}"
# ============= debug =============\  

# \========== rpm based ===============
  - name: rpm based
    block:
    - name: delete all old docker packages
      block:
        - name: Delete all old docker packages yes or no
          pause:
            prompt: "Delete all old docker packages? (y/n)"
          register: result

        - name: delete all old docker packages
          dnf:
            name:
              - docker
              - docker-client
              - docker-client-latest
              - docker-common
              - docker-latest
              - docker-latest-logrotate
              - docker-logrotate
              - docker-engine
              - podman
              - runc
              - docker-ce
              - docker-ce-cli
            state: absent
          when: result.user_input == "y"

        - name: delete old docker compose plugin
          file:
            path: /usr/local/lib/docker/cli-plugins/docker-compose 
            state: absent
          when: result.user_input == "y"

    - name: check docker
      block:
        - name: check if docker is already installed
          shell: rpm -qa | grep docker
          register: docker_check
          ignore_errors: true

        - name: return docker status
          debug:
            msg: "Docker is already installed!"
          when: docker_check.rc == 0

        - name: return docker status
          debug:
            msg: "Docker is not install!"
          when: docker_check.rc == 1

    - name: others
      block:
        - name: install prerequisites
          dnf:
            name:
              - dnf-utils
              - ca-certificates
            state: present

        - name: add repo
          shell: "sudo dnf config-manager --add-repo {{ docker_yum_repo_url }}"  
      when: docker_check.rc != 0

    - name: install docker specific version or latest
      block:
        - name: get available versions docker-ce
          shell: dnf list docker-ce --showduplicates | sort -r
          register: docker_ce_output

        - name: show versions and wait for input (docker-ce)
          pause:
            prompt: "Available versions:\n{{ docker_ce_output.stdout }}\n\nPlease enter the version you want to use. Example: 4:25.0.7-4.el7 or latest"
          register: docker_ce_input

        - name: get available versions docker-ce-cli
          shell: dnf list docker-ce-cli --showduplicates | sort -r
          register: docker_ce_cli_output

        - name: show versions and wait for input (docker-ce-cli)
          pause:
            prompt: "Available versions:\n{{ docker_ce_cli_output.stdout }}\n\nPlease enter the version you want to use. Example: 4:25.0.7-4.el7 or latest"
          register: docker_ce_cli_input

        - name: use selected version
          debug:
            msg: "You selected version: docker-ce-{{ docker_ce_input.user_input }} and docker-ce-cli-{{ docker_ce_cli_input.user_input}}"

        - name: install selected version docker-ce
          dnf:
            name:
              - "docker-ce-{{ docker_ce_input.user_input }}"
            state: present
          when: docker_ce_input.user_input != "latest"

        - name: install selected version docker-ce-cli
          dnf:
            name:
              - "docker-ce-cli-{{ docker_ce_cli_input.user_input }}"
            state: present
          when: docker_ce_cli_input.user_input != "latest"

        - name: install latest version docker-ce
          dnf:
            name:
              - docker-ce
            state: present
          when: docker_ce_input.user_input == "latest"

        - name: install latest version docker-ce-cli
          dnf:
            name:
              - docker-ce-cli
            state: present
          when: docker_ce_cli_input.user_input == "latest"
      become: yes
      when: docker_check.rc != 0
    
    - name: install docker compose plugin
      include_tasks: blocks_for_import/install_docker_compose_plugin.yml
      when: docker_check.rc != 0

    when: ansible_os_family == "RED"

    vars:
      docker_yum_repo_url: https://download.docker.com/linux/rhel/docker-ce.repo
# ======= rpm based ============/
# \========== deb based ===============
  - name: deb based
    block:
    - name: delete all old packages
      block:
        - name: delete all old docker packages yes or no
          pause:
            prompt: "Delete all old docker packages? (y/n)"
          register: result

        - name: delete all old docker packages
          apt:
            name:
              - docker.io
              - docker-compose
              - docker-compose-v2
              - docker-doc
              - podman-docker
              - containerd
              - runc
              - docker-ce
              - docker-ce-cli
            state: absent
          when: result.user_input == "y"

        - name: delete old docker compose plugin
          file:
            path: /usr/local/lib/docker/cli-plugins/docker-compose 
            state: absent
          when: result.user_input == "y"

    - name: check docker 
      block:
        - name: check if docker is already installed
          shell: systemctl | grep docker.service
          register: docker_check
          ignore_errors: true

        - name: return docker status
          debug:
            msg: "Docker is already installed!"
          when: docker_check.rc == 0

        - name: return docker status
          debug:
            msg: "Docker is not install!"
          when: docker_check.rc == 1
    - name: others
      block:
        - name: install prerequisites
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present

        - name: add GPG key for docker
          shell: |
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL {{ docker_apt_repo_url }}{{ ansible_facts.distribution | lower }}/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc
          become: yes

        - name: create file for docker repo
          file:
            path: /etc/apt/sources.list.d/docker.sources
            state: touch
            mode: u=rw,g=r,o=r

        - name: content for docker repo
          copy:
            dest: /etc/apt/sources.list.d/docker.sources
            content: |
              Types: deb
              URIs: {{ docker_apt_repo_url }}{{ ansible_facts.distribution | lower }}
              Suites: {{ ansible_facts.distribution_release}}
              Components: stable
              Signed-By: /etc/apt/keyrings/docker.asc 

        - name: update cache
          apt:
            update_cache: yes
      when: docker_check.rc != 0

    - name: install docker specific version or latest
      block:
        - name: Get available versions docker-ce
          shell: apt list --all-versions docker-ce 
          register: docker_ce_output

        - name: show versions and wait for input (docker-ce)
          pause:
            prompt: "Available versions:\n{{ docker_ce_output.stdout }}\n\nPlease enter the version you want to use. Example: 5:26.1.1-1~ubuntu.24.04~noble or latest"
          register: docker_ce_input

        - name: Get available versions docker-ce-cli
          shell: apt list --all-versions docker-ce-cli 
          register: docker_ce_cli_output

        - name: show versions and wait for input (docker-ce-cli)
          pause:
            prompt: "Available versions:\n{{ docker_ce_cli_output.stdout }}\n\nPlease enter the version you want to use. Example: 5:26.1.1-1~ubuntu.24.04~noble or latest"
          register: docker_ce_cli_input
        
        - name: use selected version
          debug:
            msg: "You selected version: docker-ce={{ docker_ce_input.user_input }} and docker-ce-cli={{ docker_ce_cli_input.user_input }}"

        - name: install selected version docker-ce
          apt:
            name:
              - "docker-ce={{ docker_ce_input.user_input }}"
            state: present
          when: docker_ce_input.user_input != "latest"

        - name: install selected version docker-ce-cli
          apt:
            name:
              - "docker-ce-cli={{ docker_ce_cli_input.user_input }}"
            state: present
          when: docker_ce_cli_input.user_input != "latest"

        - name: install latest version docker-ce
          apt:
            name:
              - docker-ce
            state: present
          when: docker_ce_input.user_input == "latest"

        - name: install latest version docker-ce-cli
          apt:
            name:
              - docker-ce-cli
            state: present
          when: docker_ce_cli_input.user_input == "latest"
      become: yes
      when: docker_check.rc != 0
    
    - name: install docker compose plugin
      include_tasks: blocks_for_import/install_docker_compose_plugin.yml
      when: docker_check.rc != 0
 
    when: ansible_os_family == "Debian"
    
    vars:
      docker_apt_repo_url: https://download.docker.com/linux/ 
#  ========== deb based ===============\
#  \========== for all ==============
  - name: add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
# ========== for all ==============\